### ISSUE TITLE
Test suite may fail (hash randomization?)

### ISSUE THREAD

**Issue by eserte** [brummett/JSON-InPlace#2]
The test suite randomly fails for perl 5.18 and greater:

```
    #   Failed test 'change nested hash value'
    #   at t/recurse.t line 65.
    #          got: '[0,1,{"b":2,"a":"changed"}]'
    #     expected: '[0,1,{"a":"changed","b":2}]'

    #   Failed test 'change string value in array to hashref'
    #   at t/recurse.t line 70.
    #          got: '[{"new":"hash"},1,{"b":2,"a":"changed"}]'
    #     expected: '[{"new":"hash"},1,{"a":"changed","b":2}]'

    #   Failed test 'change newly added hash value'
    #   at t/recurse.t line 75.
    #          got: '[{"new":"changed hash value"},1,{"b":2,"a":"changed"}]'
    #     expected: '[{"new":"changed hash value"},1,{"a":"changed","b":2}]'
    # Looks like you failed 3 tests of 4.

#   Failed test 'array of hashes'
#   at t/recurse.t line 78.
# Looks like you failed 1 test of 4. 
t/recurse.t ......
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests
```

This could be a hash randomization issue.

**Comment by brummett** [comment]
Strange.  The top-level JSON::String module and tests all use JSON's canonical mode `JSON->new->canonical` to avoid that problem.  I've been using it myself with Perl 5.10.1 and 5.20.0, and TravisCI tested it with everything from 5.8 to 5.21.

Is recurse.t the only test failing like this, or do they all randomly fail?

**Comment by eserte** [comment]
recurse.t is the only one failing. The fail reports are now visible on cpantesters, see http://matrix.cpantesters.org/?dist=JSON-String for a pass/fail overview, and here's a sample fail report: http://www.cpantesters.org/cpan/report/2e9d9042-a742-11e4-b0e8-a99c8971dd2f

**Comment by eserte** [comment]
Ah: it makes a difference if JSON::XS is installed or not. As far as I know, JSON.pm picks JSON::XS if it's installed. Maybe the canonical mode generates different output with the pure perl and the XS implementation?

**Comment by brummett** [comment]
It still worked for me whether I used the XS or PP implementations.  After a few tries, I couldn't reproduce the CPAN testers failures, so I changed the tests in 42580b to convert the strings to Perl data and compare with is_deeply().  Seems to make everything happy.
